from .auth import auth_bp
from .consultations import consult_bp
from .emergency import emergency_bp
from .pharmacy import pharmacy_bp
from .records import records_bp
from .prescriptions import prescriptions_bp
from .doctors import doctors_bp
from .ai_symptoms import ai_bp
from .admin import admin_bp
from .sync import sync_bp
from .medicine_search import medicine_bp
from .health import health_bp
from .chat import chat_bp
