import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { motion } from 'framer-motion';
import { ArrowLeft, Leaf, User, Edit2, Save, Download, FileText, Stethoscope, Pill, X } from 'lucide-react';
import { usePatient } from '../../context/PatientContext';

const ALLERGY_EMOJI = { pollen:'🌸',dust:'💨',dairy:'🥛',nuts:'🥜',penicillin:'💊',sulpha:'🧪',seafood:'🐟',latex:'🧤' };
const COND_EMOJI = { diabetes:'🩸',hypertension:'❤️',asthma:'🫁',heart:'🫀',thyroid:'🦋',arthritis:'🦴',kidney:'🫘',anemia:'🩺' };

export default function PatientProfile() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { profile, updateProfile } = usePatient();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(profile);

  const saveEdit = () => { updateProfile(draft); setEditing(false); };

  const handlePrint = () => {
    window.print();
  };

  const initials = (profile.name || 'P').split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2);

  return (
    <>
      {/* Print-only full health record */}
      <div id="print-section" className="hidden print:block p-8 text-sm font-sans">
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <h1 style={{ fontSize: 22, fontWeight: 'bold' }}>🌿 GramSwasth — Patient Health Record</h1>
          <p style={{ color: '#666' }}>Generated: {new Date().toLocaleDateString('en-IN', { dateStyle: 'long' })}</p>
        </div>
        <h2 style={{ fontSize: 16, borderBottom: '1px solid #ccc', paddingBottom: 4, marginBottom: 12 }}>Patient Details</h2>
        <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: 20 }}>
          {[
            ['Full Name', profile.name || '—'], ['Age', profile.age || '—'], ['Gender', profile.gender || '—'],
            ['Phone', profile.phone || '—'], ['Village', profile.village || '—'], ['State', profile.state || '—'],
            ['Blood Type', profile.bloodType || '—'],
            ['Allergies', profile.allergies?.length ? profile.allergies.join(', ') : 'None'],
            ['Chronic Conditions', profile.conditions?.length ? profile.conditions.join(', ') : 'None'],
            ['Current Medications', profile.currentMedications || 'None'],
            ['Emergency Contact', profile.emergencyContactName ? `${profile.emergencyContactName} — ${profile.emergencyContactPhone}` : '—'],
          ].map(([k, v]) => (
            <tr key={k} style={{ borderBottom: '1px solid #eee' }}>
              <td style={{ padding: '6px 8px', color: '#666', width: '40%', fontWeight: 500 }}>{k}</td>
              <td style={{ padding: '6px 8px', fontWeight: 600 }}>{v}</td>
            </tr>
          ))}
        </table>
        <h2 style={{ fontSize: 16, borderBottom: '1px solid #ccc', paddingBottom: 4, marginBottom: 12 }}>Medical History & Prescriptions</h2>
        {(profile.history || []).map((h, i) => (
          <div key={i} style={{ border: '1px solid #ddd', borderRadius: 8, padding: '12px 16px', marginBottom: 12 }}>
            <p style={{ fontWeight: 'bold', fontSize: 14 }}>{h.diagnosis} — {h.doctor}</p>
            <p style={{ color: '#666', fontSize: 12, marginBottom: 8 }}>{h.date}</p>
            {h.medicines.map((m, j) => <p key={j} style={{ fontSize: 13, margin: '2px 0' }}>• {m}</p>)}
            <p style={{ marginTop: 6, fontSize: 12, color: '#555', fontStyle: 'italic' }}>{h.instructions}</p>
          </div>
        ))}
        <p style={{ textAlign: 'center', color: '#999', fontSize: 11, marginTop: 24 }}>
          This document is auto-generated by GramSwasth. For official use, please verify with your doctor.
        </p>
      </div>

      {/* App UI — hidden when printing */}
      <div className="min-h-dvh bg-white flex flex-col print:hidden">
        <header className="flex items-center gap-3 px-4 py-3 border-b border-cream-200 pt-safe-top sticky top-0 z-20 bg-white">
          <button onClick={() => navigate('/patient/dashboard')} className="p-2 rounded-xl hover:bg-cream-100"><ArrowLeft size={20} className="text-gray-500" /></button>
          <div className="w-7 h-7 bg-sage-500 rounded-lg flex items-center justify-center"><Leaf size={13} className="text-white" /></div>
          <h1 className="font-bold text-gray-800 flex-1">My Profile</h1>
          {editing
            ? <button onClick={saveEdit} className="chip bg-sage-500 text-white flex items-center gap-1"><Save size={13} /> Save</button>
            : <button onClick={() => { setDraft(profile); setEditing(true); }} className="chip bg-cream-200 text-sage-700 flex items-center gap-1"><Edit2 size={13} /> Edit</button>
          }
        </header>

        <main className="flex-1 flex flex-col gap-4 px-4 py-5 max-w-md mx-auto w-full">
          {/* Avatar */}
          <div className="flex items-center gap-4">
            <div className="w-20 h-20 rounded-full bg-sage-500 flex items-center justify-center text-white text-2xl font-bold flex-shrink-0">
              {initials}
            </div>
            <div>
              <div className="font-bold text-gray-800 text-lg">{profile.name || 'Patient'}</div>
              <div className="text-sm text-gray-500">{profile.village}, {profile.state}</div>
              <div className="flex items-center gap-2 mt-1">
                {profile.bloodType && <span className="chip bg-red-100 text-red-600 font-bold">🩸 {profile.bloodType}</span>}
                {profile.gender && <span className="chip bg-cream-200 text-gray-600">{profile.gender}</span>}
              </div>
            </div>
          </div>

          {/* Personal info */}
          <div className="gs-card flex flex-col gap-3">
            <h2 className="font-semibold text-gray-700 text-sm flex items-center gap-1.5"><User size={14} /> Personal Information</h2>
            {editing ? (
              <div className="flex flex-col gap-2">
                {[
                  { label: 'Name', key: 'name', type: 'text' },
                  { label: 'Age', key: 'age', type: 'number' },
                  { label: 'Phone', key: 'phone', type: 'tel' },
                  { label: 'Village', key: 'village', type: 'text' },
                  { label: 'Blood Group', key: 'blood_group', type: 'text' },
                  { label: 'Emergency Contact Phone', key: 'emergency_contact_phone', type: 'tel' },
                ].map(f => (
                  <div key={f.key} className="flex flex-col gap-0.5">
                    <label className="text-xs text-gray-400">{f.label}</label>
                    <input type={f.type} className="gs-input !text-sm !py-2" value={draft[f.key] || ''}
                      onChange={e => setDraft(d => ({ ...d, [f.key]: e.target.value }))} />
                  </div>
                ))}
              </div>
            ) : (
              <div className="grid grid-cols-2 gap-2">
                {[
                  ['Age', profile.age],['Phone', profile.phone],
                  ['Village', profile.village],['Blood Group', profile.blood_group],
                ].map(([l, v]) => (
                  <div key={l}><p className="text-xs text-gray-400">{l}</p><p className="text-sm font-semibold text-gray-800">{v || '—'}</p></div>
                ))}
              </div>
            )}
          </div>

          {/* Medical details */}
          <div className="gs-card flex flex-col gap-3">
            <h2 className="font-semibold text-gray-700 text-sm flex items-center gap-1.5"><Stethoscope size={14} /> Medical Details</h2>
            <div>
              <p className="text-xs text-gray-400 mb-1.5">Allergies</p>
              {profile.allergies?.length ? (
                <div className="flex flex-wrap gap-1.5">
                  {profile.allergies.map(a => <span key={a} className="chip bg-amber-100 text-amber-700">{ALLERGY_EMOJI[a] || '⚠️'} {a}</span>) || 'None recorded'}
                </div>
              ) : <p className="text-sm text-gray-500">None recorded</p>}
            </div>
            <div>
              <p className="text-xs text-gray-400 mb-1">Emergency Contact</p>
              <p className="text-sm font-semibold text-gray-800">{profile.emergency_contact_name || '—'}</p>
              <p className="text-sm text-gray-500">{profile.emergency_contact_phone || ''}</p>
            </div>
          </div>

          {/* Medical history */}
          <div className="flex flex-col gap-2">
            <h2 className="font-semibold text-gray-700 text-sm flex items-center gap-1.5"><FileText size={14} /> Medical History</h2>
            {(profile.history || []).map((h, i) => (
              <div key={i} className="gs-card !py-3 flex flex-col gap-2">
                <div className="flex items-start justify-between">
                  <div>
                    <div className="font-semibold text-sm text-gray-800">{h.diagnosis}</div>
                    <div className="text-xs text-gray-500">{h.doctor} · {h.date}</div>
                  </div>
                </div>
                {h.medicines.map((m, j) => (
                  <div key={j} className="flex items-center gap-1.5 text-xs text-gray-600"><Pill size={11} className="text-sage-400" /> {m}</div>
                ))}
                <div className="text-xs text-gray-400 italic">{h.instructions}</div>
              </div>
            ))}
          </div>

          {/* PDF download */}
          <button className="btn-primary flex items-center justify-center gap-2 mt-1" onClick={handlePrint}>
            <Download size={16} /> Download Full Health Record as PDF
          </button>
          <p className="text-xs text-gray-400 text-center">Includes your profile, medical history & all prescriptions</p>
        </main>
      </div>
    </>
  );
}
